# Site settings
title: Lin Li
email: lilin950715@126.com
description: Lin is from Beijing, China
url: http://lilin95.github.io
github_username: lilin95

# Build settings
markdown: kramdown
permalink: pretty
